export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_SINGLE_TOURNAMENTS_SUCCESS = 'GET_SINGLE_TOURNAMENTS_SUCCESS';
export const GET_MULTI_TOURNAMENTS_SUCCESS = 'GET_MULTI_TOURNAMENTS_SUCCESS';
