export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_TOURNAMENTS_SUCCESS = 'GET_TOURNAMENTS_SUCCESS';
export const SORT_SINGLE_TOURNAMENTS = 'SORT_SINGLE_TOURNAMENTS';
export const SORT_MULTI_TOURNAMENTS = 'SORT_MULTI_TOURNAMENTS';
export const LOAD_MORE_TOURNAMENTS_SUCCESS = 'LOAD_MORE_TOURNAMENTS_SUCCESS';
